# Generated by Django 5.1.3 on 2024-11-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_blogpost_status_service_is_active_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, default='No subject', max_length=200),
        ),
    ]
